#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "mbr/app/app.h"
#include "mbr/ui_projector/ui_projector.h"
#define ID(v) ((mbr_mouse_id_t){(uint64_t)(v)})
#define SESSION(v,g) ((mbr_mouse_session_id_t){ID(v),(uint32_t)(g)})
static void tap(mbr_ux_model_t*m,mbr_control_t c,mbr_ux_effects_t*e){mbr_ux_input(m,c,true,e);mbr_ux_input(m,c,false,e);}
static void effect(const mbr_ux_effects_t*e,size_t i,mbr_ux_effect_kind_t k){assert(i<e->count);assert(e->items[i].kind==k);}

static void release_help_lock(void){mbr_saved_mouse_t s[2];mbr_ux_model_t m;mbr_ux_effects_t e;mbr_ux_model_init(&m,s,2);assert(mbr_mouse_registry_add(&m.registry,(mbr_saved_mouse_t){ID(1),"A",MBR_PROFILE_PASSTHROUGH}));assert(mbr_mouse_session_slot_promote(&m.live,SESSION(1,1)));m.screen=MBR_SCREEN_HOME_CONNECTED;mbr_ux_input(&m,MBR_CONTROL_KEY_X,true,&e);assert(m.screen==MBR_SCREEN_HOME_CONNECTED);mbr_ux_input(&m,MBR_CONTROL_KEY_X,false,&e);assert(m.screen==MBR_SCREEN_HELP_HOME_CONNECTED);tap(&m,MBR_CONTROL_KEY_Y,&e);assert(m.screen==MBR_SCREEN_HOME_CONNECTED);m.screen=MBR_SCREEN_PAIR_NEW;tap(&m,MBR_CONTROL_KEY_Y,&e);assert(m.interaction.locked);tap(&m,MBR_CONTROL_KEY_B,&e);assert(!m.interaction.locked);assert(m.screen==MBR_SCREEN_PAIR_NEW);m.screen=MBR_SCREEN_LEARN_THE_KEYS;tap(&m,MBR_CONTROL_KEY_B,&e);assert(m.interaction.locked);tap(&m,MBR_CONTROL_KEY_A,&e);assert(m.interaction.locked);tap(&m,MBR_CONTROL_KEY_X,&e);assert(!m.interaction.locked);assert(m.screen==MBR_SCREEN_LEARN_THE_KEYS);}

static void home_and_stale(void){mbr_saved_mouse_t s[4];mbr_ux_model_t m;mbr_ux_effects_t e;mbr_ux_model_init(&m,s,4);mbr_ux_boot(&m,&e);assert(m.screen==MBR_SCREEN_SEARCHING_FIRST);assert(e.count==1);effect(&e,0,MBR_UX_EFFECT_START_SEARCH);assert(e.items[0].purpose==MBR_SEARCH_FIRST_MOUSE&&e.items[0].duration_ms==8000u);uint32_t t=e.items[0].transaction_id;mbr_ux_effects_clear(&e);mbr_ux_search_expired(&m,t+9,&e);assert(m.pairing.transaction_id==t&&e.count==0);mbr_ux_search_expired(&m,t,&e);assert(m.screen==MBR_SCREEN_SEARCHING_FIRST&&e.count==1&&e.items[0].transaction_id!=t);t=e.items[0].transaction_id;assert(mbr_ux_first_mouse_ready(&m,t,(mbr_saved_mouse_t){ID(1),"A",MBR_PROFILE_PASSTHROUGH},SESSION(1,1)));assert(m.screen==MBR_SCREEN_FIRST_MOUSE_CONNECTED&&mbr_mouse_session_ready_count(&m.live)==1);tap(&m,MBR_CONTROL_KEY_Y,&e);assert(m.screen==MBR_SCREEN_HOME_CONNECTED);mbr_ux_mouse_disconnected(&m,SESSION(1,99),&e);assert(m.screen==MBR_SCREEN_HOME_CONNECTED);mbr_ux_mouse_disconnected(&m,SESSION(1,1),&e);assert(m.screen==MBR_SCREEN_HOME_SEARCHING);assert(e.count==1&&e.items[0].purpose==MBR_SEARCH_SAVED&&e.items[0].duration_ms==8000u);t=e.items[0].transaction_id;mbr_ux_search_expired(&m,t,&e);assert(m.screen==MBR_SCREEN_HOME_RETRY);tap(&m,MBR_CONTROL_KEY_A,&e);assert(m.screen==MBR_SCREEN_HOME_SEARCHING&&e.items[0].purpose==MBR_SEARCH_SAVED);}

static void pair_new(void){mbr_saved_mouse_t s[5];mbr_ux_model_t m;mbr_ux_effects_t e;mbr_ux_model_init(&m,s,5);assert(mbr_mouse_registry_add(&m.registry,(mbr_saved_mouse_t){ID(1),"A",MBR_PROFILE_STANDARD}));assert(mbr_mouse_session_slot_promote(&m.live,SESSION(1,1)));m.screen=MBR_SCREEN_HOME_RETRY;m.selection=0;tap(&m,MBR_CONTROL_JOY_PRESS,&e);assert(m.screen==MBR_SCREEN_PAIR_NEW&&m.pairing.duration_ms==15000u&&mbr_mouse_session_ready_count(&m.live)==1);uint32_t t=m.pairing.transaction_id;assert(!mbr_ux_pair_new_candidate_ready(&m,t,ID(1),SESSION(1,2)));assert(!mbr_ux_pair_new_candidate_ready(&m,t+1,ID(2),SESSION(2,1)));assert(mbr_ux_pair_new_candidate_ready(&m,t,ID(2),SESSION(2,1)));assert(m.pairing.candidate.replacement_ready&&mbr_mouse_session_ready_count(&m.live)==1);assert(mbr_ux_pair_new_handoff_committed(&m,t,(mbr_saved_mouse_t){ID(2),"B",MBR_PROFILE_PASSTHROUGH},SESSION(2,1)));assert(m.screen==MBR_SCREEN_HOME_CONNECTED&&mbr_mouse_id_equal(m.live.session_id.mouse_id,ID(2))&&m.registry.count==2);assert(mbr_mouse_registry_find(&m.registry,ID(1))!=NULL);
    m.screen=MBR_SCREEN_HOME_RETRY;m.selection=0;tap(&m,MBR_CONTROL_JOY_PRESS,&e);t=m.pairing.transaction_id;mbr_ux_search_expired(&m,t,&e);assert(m.screen==MBR_SCREEN_RETRY_PAIR_NEW&&mbr_mouse_session_ready_count(&m.live)==1);tap(&m,MBR_CONTROL_KEY_B,&e);assert(m.screen==MBR_SCREEN_HOME_CONNECTED);
    m.screen=MBR_SCREEN_HOME_RETRY;m.selection=0;tap(&m,MBR_CONTROL_JOY_PRESS,&e);assert(m.screen==MBR_SCREEN_PAIR_NEW);mbr_mouse_session_id_t live=m.live.session_id;mbr_ux_mouse_disconnected(&m,live,&e);assert(m.screen==MBR_SCREEN_PAIR_NEW);tap(&m,MBR_CONTROL_KEY_B,&e);assert(m.screen==MBR_SCREEN_HOME_SEARCHING&&m.pairing.purpose==MBR_SEARCH_SAVED);}

static void profiles_custom_remove(void){mbr_saved_mouse_t s[4];mbr_ux_model_t m;mbr_ux_effects_t e;mbr_ui_frame_t f;mbr_ux_model_init(&m,s,4);assert(mbr_mouse_registry_add(&m.registry,(mbr_saved_mouse_t){ID(1),"A",MBR_PROFILE_STANDARD}));assert(mbr_mouse_registry_add(&m.registry,(mbr_saved_mouse_t){ID(2),"B",MBR_PROFILE_ESCAPE}));assert(mbr_mouse_session_slot_promote(&m.live,SESSION(1,1)));m.screen=MBR_SCREEN_REMAPPER_OPTIONS;m.selection=2;tap(&m,MBR_CONTROL_JOY_PRESS,&e);assert(m.screen==MBR_SCREEN_ESCAPE_NOT_ACTIVE);tap(&m,MBR_CONTROL_KEY_A,&e);assert(m.screen==MBR_SCREEN_ESCAPE_NOT_ACTIVE&&m.pending_profile_apply);effect(&e,0,MBR_UX_EFFECT_APPLY_PROFILE);mbr_ux_profile_apply_failed(&m,ID(1),MBR_PROFILE_ESCAPE);assert(m.screen==MBR_SCREEN_ESCAPE_NOT_ACTIVE);tap(&m,MBR_CONTROL_KEY_A,&e);assert(mbr_ux_profile_apply_confirmed(&m,ID(1),MBR_PROFILE_ESCAPE));assert(m.screen==MBR_SCREEN_ESCAPE_ACTIVE);tap(&m,MBR_CONTROL_KEY_Y,&e);assert(!m.interaction.locked);tap(&m,MBR_CONTROL_JOY_LEFT,&e);assert(m.screen==MBR_SCREEN_HOME_CONNECTED);
    m.screen=MBR_SCREEN_CUSTOM_EDIT;m.selection=MBR_MOUSE_SOURCE_LEFT;tap(&m,MBR_CONTROL_JOY_PRESS,&e);assert(m.screen==MBR_SCREEN_LEFT);m.selection=MBR_MOUSE_TARGET_ESCAPE;tap(&m,MBR_CONTROL_KEY_A,&e);assert(m.screen==MBR_SCREEN_CUSTOM_EDIT&&m.custom_draft.targets[MBR_MOUSE_SOURCE_LEFT]==MBR_MOUSE_TARGET_ESCAPE);effect(&e,0,MBR_UX_EFFECT_SAVE_CUSTOM_DRAFT);mbr_ui_project(&m,&f);assert(!strcmp(f.rows[1].text," LEFT IS ESCAPE"));
    m.remove_mouse_id=ID(2);m.screen=MBR_SCREEN_REMOVE_THIS;tap(&m,MBR_CONTROL_KEY_A,&e);assert(m.registry.count==2);effect(&e,0,MBR_UX_EFFECT_REMOVE_MOUSE);assert(mbr_ux_remove_confirmed(&m,ID(2),&e));assert(m.registry.count==1&&m.screen==MBR_SCREEN_SAVED_DEVICES);}

int main(void){release_help_lock();home_and_stale();pair_new();profiles_custom_remove();puts("MBR-02 behavior: PASS");return 0;}
