#pragma once
#include "mbr/domain/domain.h"
typedef enum {
 MBR_SCREEN_SEARCHING_FIRST,
 MBR_SCREEN_FIRST_MOUSE_CONNECTED,
 MBR_SCREEN_HOME_SEARCHING,
 MBR_SCREEN_HOME_SEARCHING_HELP,
 MBR_SCREEN_HOME_RETRY,
 MBR_SCREEN_HOME_RETRY_HELP,
 MBR_SCREEN_PAIR_NEW,
 MBR_SCREEN_HELP_PAIR_NEW,
 MBR_SCREEN_RETRY_PAIR_NEW,
 MBR_SCREEN_HELP_RETRY_PAIR_NEW,
 MBR_SCREEN_HOME_CONNECTED,
 MBR_SCREEN_HELP_HOME_CONNECTED,
 MBR_SCREEN_REMAPPER_OPTIONS,
 MBR_SCREEN_HELP_REMAPPER_OPTIONS,
 MBR_SCREEN_PASSTHROUGH_ACTIVE,
 MBR_SCREEN_PASSTHROUGH_NOT_ACTIVE,
 MBR_SCREEN_STANDARD_NOT_ACTIVE,
 MBR_SCREEN_STANDARD_ACTIVE,
 MBR_SCREEN_ESCAPE_NOT_ACTIVE,
 MBR_SCREEN_ESCAPE_ACTIVE,
 MBR_SCREEN_CUSTOM_EDIT,
 MBR_SCREEN_LEFT,
 MBR_SCREEN_RIGHT,
 MBR_SCREEN_MIDDLE,
 MBR_SCREEN_FORWARD,
 MBR_SCREEN_BACKWARD,
 MBR_SCREEN_SAVED_DEVICES,
 MBR_SCREEN_REMOVE_THIS,
 MBR_SCREEN_HELP_REMOVE_THIS,
 MBR_SCREEN_LEARN_THE_KEYS,
 MBR_SCREEN_COUNT
} MbrScreen;
typedef struct { const char *id; const char *rows[9]; } MbrScreenTemplate;
extern const MbrScreenTemplate mbr_screens[MBR_SCREEN_COUNT];
