(function(global){"use strict";
const WIDTH=240,HEIGHT=240,NAME_CAPACITY=64,SAVED_CAPACITY=16,SAVED_MS=8000,PAIR_MS=15000;
const CONTROL=Object.freeze({up:0,down:1,left:2,right:3,press:4,a:5,b:6,x:7,y:8});
const PROFILE=Object.freeze({PASSTHROUGH:0,STANDARD:1,ESCAPE:2,CUSTOM:3});
const TARGET=Object.freeze({LEFT:0,RIGHT:1,MIDDLE:2,ESCAPE:3,FORWARD:4,BACKWARD:5});
const SEARCH=Object.freeze({NONE:0,FIRST:1,SAVED:2,NEW:3});
const TONE=Object.freeze({TITLE:0,BODY:1,ACTION:2,WHITE:3,CYAN:4});
const SCREEN_TEMPLATES=[
["searching-first",["SEARCHING FIRST MOUSE","PRESS TO LEARN KEYS","WHILE WAIT CONNECTION","       JOY UP","  JOY    JOY    JOY","  LEFT  PRESS  RIGHT","      JOY DOWN"," KEY A         KEY X"," KEY B         KEY Y"]],
["first-mouse-connected",["FIRST MOUSE CONNECTED","       JOY UP","  JOY    JOY    JOY","  LEFT  PRESS  RIGHT","      JOY DOWN","               KEY A","LOCK SCREEN    KEY B"," AND UNLOCK    KEY X","  OPEN HOME -> KEY Y"]],
["home-searching",["SEARCHING SAVED MOUSE"," PAIR NEW MOUSE"," SAVED DEVICES"," LEARN THE KEYS","","KEY B: CANCEL SEARCH","JOY UP / DOWN: SELECT","JOY PRESS: ACCESS","KEY X: HELP"]],
["home-searching-help",["HOME SEARCHING HELP","THE MATCHING ATTEMPT","TOOK PLACE ONLY FOR","DEVICES ALREADY SAVED","IN THE PREFERENCES,","BUT NOT FOR DEVICES","THAT WERE NOT SAVED.","","ANY KEY: BACK"]],
["home-retry",["DEVICE NOT FOUND"," PAIR NEW MOUSE"," SAVED DEVICES"," LEARN THE KEYS","","KEY A: RETRY SEARCH","JOY UP / DOWN: SELECT","JOY PRESS: ACCESS","KEY X: HELP"]],
["home-retry-help",["HOME RETRY HELP","THE MATCHING ATTEMPT","TOOK PLACE ONLY FOR","DEVICES ALREADY SAVED","IN THE PREFERENCES,","BUT NOT FOR DEVICES","THAT WERE NOT SAVED.","","ANY KEY: BACK"]],
["pair-new",["PAIR NEW MOUSE","TRYING TO CONNECT","A NEW MOUSE THAT","IS NOT LISTED","IN SAVED DEVICES","","KEY B: CANCEL","KEY X: HELP","KEY Y: LOCK"]],
["help-pair-new",["PAIR NEW DEVICE HELP","TO CONNECT A SAVED","DEVICE, FIRST UNPLUG","CURRENTLY CONNECTED","MOUSE AND PRESS THE","KEY B TO BACK UNTIL","SEARCHING APPEARS.","","ANY KEY: BACK"]],
["retry-pair-new",["PAIR NEW MOUSE","NO NEW MOUSE OUTSIDE","THE LIST OF SAVED","DEVICES WAS FOUND","","KEY A: RETRY NEW PAIR","KEY B: BACK TRY SAVED","KEY X: HELP","KEY Y: LOCK"]],
["help-retry-pair-new",["DEVICE NOT FOUND HELP","TO CONNECT A SAVED","DEVICE, FIRST UNPLUG","CURRENTLY CONNECTED","MOUSE AND PRESS THE","KEY B TO BACK UNTIL","SEARCHING APPEARS.","","ANY KEY: BACK"]],
["home-connected",["LOGITECH LIFT"," PAIR NEW MOUSE"," REMAPPED TO ESCAPE"," SAVED DEVICES"," LEARN THE KEYS","","JOY UP / DOWN: SELECT","JOY PRESS: ACCESS","KEY X: HELP TO REMOVE"]],
["help-home-connected",["HOME CONNECTED HELP","TO DISCONNECT THE","CURRENTLY CONNECTED","MOUSE, NAVIGATE TO:","SAVED DEVICES >","(MOUSE PAGE) > REMOVE","DEVICE > REMOVE","","ANY KEY: BACK"]],
["remapper-options",["MOUSE OPTIONS"," PASSTHROUGH"," STANDARD REMAP"," ESCAPE REMAP"," CUSTOM REMAP","","JOY PRESS: ACCESS","JOY LEFT: BACK","KEY X: HELP"]],
["help-remapper-options",["REMAPPER OPTIONS HELP","CHOOSE FROM THE","OPTIONS TO CHANGE THE","FUNCTIONS OF THE","MOUSE BUTTONS.","PASSTHROUGH IS THE","DEFAULT OPTION.","","ANY KEY: BACK"]],
["passthrough-active",["PASSTHROUGH ACTIVE","ORIGINAL MOUSE","BUTTONS POSITION","ARE ACTIVE NOW","","","","KEY B: BACK","KEY Y: LOCK"]],
["passthrough-not-active",["APPLY PASSTHROUGH","ORIGINAL MOUSE","BUTTONS POSITION","ARE NOT ACTIVE","","","KEY A: APPLY","KEY B: CANCEL","KEY Y: LOCK"]],
["standard-not-active",["APPLY STANDARD REMAP","FORWARD IS LEFT","LEFT IS FORWARD","BACKWARD IS RIGHT","RIGHT IS BACKWARD","","KEY A: APPLY","KEY B: CANCEL","KEY Y: LOCK"]],
["standard-active",["STANDARD REMAP ACTIVE","FORWARD IS LEFT","LEFT IS FORWARD","BACKWARD IS RIGHT","RIGHT IS BACKWARD","","","KEY B: BACK","KEY Y: LOCK"]],
["escape-not-active",["APPLY ESCAPE REMAP","FORWARD IS LEFT","BACKWARD IS RIGHT","LEFT IS ESCAPE","RIGHT IS BACKWARD","MIDDLE IS FORWARD","","KEY A: APPLY","KEY B: CANCEL"]],
["escape-active",["ESCAPE APPLIED ACTIVE","FORWARD IS LEFT","BACKWARD IS RIGHT","LEFT IS ESCAPE","RIGHT IS BACKWARD","MIDDLE IS FORWARD","","KEY B: BACK","JOY LEFT: GO TO HOME"]],
["custom-edit",["EDIT CUSTOM REMAP"," LEFT IS LEFT"," RIGHT IS RIGHT"," MIDDLE IS MIDDLE"," FORWARD IS FORWARD"," BACKWARD IS BACKWARD","","JOY PRESS: ACCESS","KEY A: APPLY CUSTOM"]],
["left",["LEFT WILL BECOME"," LEFT"," RIGHT"," MIDDLE"," ESCAPE"," FORWARD"," BACKWARD","","KEY A: APPLY AND BACK"]],
["right",["RIGHT WILL BECOME"," LEFT"," RIGHT"," MIDDLE"," ESCAPE"," FORWARD"," BACKWARD","","KEY A: APPLY AND BACK"]],
["middle",["MIDDLE WILL BECOME"," LEFT"," RIGHT"," MIDDLE"," ESCAPE"," FORWARD"," BACKWARD","","KEY A: APPLY AND BACK"]],
["forward",["FORWARD WILL BECOME"," LEFT"," RIGHT"," MIDDLE"," ESCAPE"," FORWARD"," BACKWARD","","KEY A: APPLY AND BACK"]],
["backward",["BACKWARD WILL BECOME"," LEFT"," RIGHT"," MIDDLE"," ESCAPE"," FORWARD"," BACKWARD","","KEY A: APPLY AND BACK"]],
["saved-devices",["3 OF 4","LOGITECH LIFT","STATUS: CONNECTED","PROFILE: STANDARD"," REMOVE DEVICE","","JOY RIGHT\\LEFT: PAGE","JOY PRESS: ACCESS","KEY B: BACK"]],
["remove-this",["REMOVE THIS MOUSE","LOGITECH LIFT","","PAIRING AND MAPPINGS","WILL BE DELETED","","KEY A: REMOVE","KEY B: CANCEL","KEY X: HELP"]],
["help-remove-this",["REMOVE MOUSE HELP","COMPLETELY REMOVE THE","AUTOMATIC CONNECTION","WHEN TURNING ON THE","DEVICE AND DELETE ITS","BUTTON REMAPPING","PROFILE.","","ANY KEY: BACK"]],
["learn-the-keys",["PRESS TO LEARN KEYS","       JOY UP","  JOY    JOY    JOY","  LEFT  PRESS  RIGHT","      JOY DOWN","               KEY A","LOCK SCREEN    KEY B"," AND UNLOCK    KEY X","  OPEN HOME -> KEY Y"]]];
const SCREEN=Object.freeze(Object.fromEntries(SCREEN_TEMPLATES.map((x,i)=>[x[0],i]))),SCREEN_IDS=Object.freeze(SCREEN_TEMPLATES.map(x=>x[0]));
const ALPHA=[[14,17,17,31,17,17,17],[30,17,17,30,17,17,30],[15,16,16,16,16,16,15],[30,17,17,17,17,17,30],[31,16,16,30,16,16,31],[31,16,16,30,16,16,16],[15,16,16,23,17,17,15],[17,17,17,31,17,17,17],[31,4,4,4,4,4,31],[7,2,2,2,18,18,12],[17,18,20,24,20,18,17],[16,16,16,16,16,16,31],[17,27,21,21,17,17,17],[17,25,21,19,17,17,17],[14,17,17,17,17,17,14],[30,17,17,30,16,16,16],[14,17,17,17,21,18,13],[30,17,17,30,20,18,17],[15,16,16,14,1,1,30],[31,4,4,4,4,4,4],[17,17,17,17,17,17,14],[17,17,17,17,17,10,4],[17,17,17,21,21,21,10],[17,17,10,4,10,17,17],[17,17,10,4,4,4,4],[31,1,2,4,8,16,31]];
const DIGIT=[[14,17,19,21,25,17,14],[4,12,4,4,4,4,14],[14,17,1,2,4,8,31],[30,1,1,14,1,1,30],[2,6,10,18,31,2,2],[31,16,16,30,1,1,30],[14,16,16,30,17,17,14],[31,1,2,4,8,8,8],[14,17,17,14,17,17,14],[14,17,17,15,1,1,14]];
const RGB565=Object.freeze({BLACK:0,DARK_MAGENTA:0x0801,LIGHT_GRAY:0xc618,TONES:[0xf81f,0xffb8,0xc618,0xffff,0x07ff]});
const TARGET_NAMES=["LEFT","RIGHT","MIDDLE","ESCAPE","FORWARD","BACKWARD"],SOURCE_NAMES=["LEFT","RIGHT","MIDDLE","FORWARD","BACKWARD"],PROFILE_NAMES=["PASSTHROUGH","STANDARD","ESCAPE","CUSTOM"],TOKEN_NAMES=["JOY UP","JOY DOWN","JOY LEFT","JOY RIGHT","JOY PRESS","KEY A","KEY B","KEY X","KEY Y"];
const clone=v=>JSON.parse(JSON.stringify(v)),screenRows=s=>SCREEN_TEMPLATES[s][1],screenId=s=>SCREEN_TEMPLATES[s]?SCREEN_TEMPLATES[s][0]:"invalid",findScreen=id=>Object.prototype.hasOwnProperty.call(SCREEN,id)?SCREEN[id]:-1;
const isDidactic=s=>s===SCREEN["searching-first"]||s===SCREEN["first-mouse-connected"]||s===SCREEN["learn-the-keys"];
const isHome=s=>[SCREEN["searching-first"],SCREEN["home-connected"],SCREEN["home-searching"],SCREEN["home-retry"]].includes(s);
const isHelp=s=>[SCREEN["home-searching-help"],SCREEN["home-retry-help"],SCREEN["help-pair-new"],SCREEN["help-retry-pair-new"],SCREEN["help-home-connected"],SCREEN["help-remapper-options"],SCREEN["help-remove-this"]].includes(s);
function displayName(name){const allowed=new Set(" -:.=/\\><?!,()");let out="",useful=false;for(const raw of String(name||"").slice(0,NAME_CAPACITY)){if(out.length>=21)break;const c=raw>="a"&&raw<="z"?raw.toUpperCase():raw;if(/[A-Z0-9]/.test(c)||allowed.has(c)){out+=c;if(c!==" ")useful=true}}return useful?out:"UNKNOWN MOUSE"}
function homeTitle(name){const upper=String(name||"").slice(0,NAME_CAPACITY).toUpperCase(),word=c=>!!c&&/[A-Z0-9_]/.test(c);let has=false;for(let i=0;i+5<=upper.length;i++)if(upper.slice(i,i+5)==="MOUSE"&&!word(upper[i-1])&&!word(upper[i+5])){has=true;break}let out=displayName(name);if(out==="UNKNOWN MOUSE")return out;out=out.slice(0,15).replace(/ +$/,"");return has?out:out+" MOUSE"}
function createApp(now=0){return{registry:[],live:null,nextSession:0,search:{purpose:SEARCH.NONE,generation:0,started:0,duration:0},screen:SCREEN["searching-first"],helpOwner:SCREEN["searching-first"],helpSelection:0,epoch:0,now,selection:0,page:0,source:0,locked:false,customDirty:false,draft:[0,1,2,4,5],custom:[0,1,2,4,5],pressed:0,owners:Array(9).fill(0)}}
function createPersistent(){return{registry:[],custom:[0,1,2,4,5],draft:[0,1,2,4,5],dirty:false}}
function snapshot(a){return{registry:clone(a.registry),custom:[...a.custom],draft:[...a.draft],dirty:!!a.customDirty}}
function show(a,s){a.screen=s;a.selection=0;a.epoch=(a.epoch+1)>>>0}function searchStart(a,p){a.search.generation=(a.search.generation+1)>>>0;if(!a.search.generation)a.search.generation=1;a.search.purpose=p;a.search.started=a.now>>>0;a.search.duration=p===SEARCH.NEW?PAIR_MS:SAVED_MS}function searchCancel(a){a.search.purpose=SEARCH.NONE}function searchExpired(a){return a.search.purpose!==SEARCH.NONE&&((a.now-a.search.started)>>>0)>=a.search.duration}function registryFind(a,id){return a.registry.findIndex(m=>m.id===id)}function liveProfile(a){if(!a.live)return PROFILE.PASSTHROUGH;const i=registryFind(a,a.live.mouse);return i<0?PROFILE.PASSTHROUGH:a.registry[i].profile}
function home(a){if(!a.registry.length){show(a,SCREEN["searching-first"]);if(a.search.purpose!==SEARCH.FIRST)searchStart(a,SEARCH.FIRST)}else if(a.live){searchCancel(a);show(a,SCREEN["home-connected"])}else{show(a,SCREEN["home-searching"]);searchStart(a,SEARCH.SAVED)}}function restore(a,p){a.registry=clone(p.registry||[]);a.custom=[...(p.custom||[0,1,2,4,5])];a.draft=[...(p.draft||[0,1,2,4,5])];a.customDirty=!!p.dirty;home(a)}function pair(a){show(a,SCREEN["pair-new"]);searchStart(a,SEARCH.NEW)}
function optionsCount(s){if(s===SCREEN["home-connected"]||s===SCREEN["remapper-options"])return 4;if(s===SCREEN["home-searching"]||s===SCREEN["home-retry"])return 3;if(s===SCREEN["custom-edit"])return 5;if(s>=SCREEN.left&&s<=SCREEN.backward)return 6;return 0}
function profilePage(a,p){const active=liveProfile(a)===p,off=[SCREEN["passthrough-not-active"],SCREEN["standard-not-active"],SCREEN["escape-not-active"],SCREEN["custom-edit"]],on=[SCREEN["passthrough-active"],SCREEN["standard-active"],SCREEN["escape-active"],SCREEN["custom-edit"]];show(a,active?on[p]:off[p])}
function contextualHelp(a){const m=new Map([[SCREEN["home-searching"],SCREEN["home-searching-help"]],[SCREEN["home-retry"],SCREEN["home-retry-help"]],[SCREEN["pair-new"],SCREEN["help-pair-new"]],[SCREEN["retry-pair-new"],SCREEN["help-retry-pair-new"]],[SCREEN["home-connected"],SCREEN["help-home-connected"]],[SCREEN["remapper-options"],SCREEN["help-remapper-options"]],[SCREEN["remove-this"],SCREEN["help-remove-this"]]]);if(!m.has(a.screen))return;a.helpOwner=a.screen;a.helpSelection=a.selection;show(a,m.get(a.screen))}
function controlEvent(a,control,down){const c=typeof control==="string"?CONTROL[control]:control;if(!Number.isInteger(c)||c<0||c>=9)return false;const bit=1<<c;if(down){if(!(a.pressed&bit))a.owners[c]=a.epoch;a.pressed|=bit;return false}const act=!!(a.pressed&bit)&&a.owners[c]===a.epoch;a.pressed&=~bit;if(!act)return false;if(a.locked){if(!isDidactic(a.screen)||c===CONTROL.x){a.locked=false;a.epoch=(a.epoch+1)>>>0}return true}if(isHelp(a.screen)){if(a.helpOwner===SCREEN["home-searching"]&&a.search.purpose===SEARCH.NONE)home(a);else show(a,a.helpOwner);const n=optionsCount(a.screen);a.selection=n?a.helpSelection%n:0;return true}if(a.screen===SCREEN["searching-first"])return true;if(a.screen===SCREEN["first-mouse-connected"]||a.screen===SCREEN["learn-the-keys"]){if(c===CONTROL.b){a.locked=true;a.epoch=(a.epoch+1)>>>0}if(c===CONTROL.y)home(a);return true}if(c===CONTROL.x){contextualHelp(a);return true}if(c===CONTROL.y){if(screenRows(a.screen).slice(1).some(r=>r==="KEY Y: LOCK")){a.locked=true;a.epoch=(a.epoch+1)>>>0}return true}const n=optionsCount(a.screen);if(n&&(c===CONTROL.up||c===CONTROL.down)){a.selection=(a.selection+n+(c===CONTROL.up?-1:1))%n;return true}
switch(a.screen){case SCREEN["home-searching"]:case SCREEN["home-retry"]:case SCREEN["home-connected"]:if(c===CONTROL.b&&a.screen===SCREEN["home-searching"]){searchCancel(a);show(a,SCREEN["home-retry"])}else if(c===CONTROL.a&&a.screen===SCREEN["home-retry"])home(a);else if(c===CONTROL.press){const sel=a.selection;if(sel===0)pair(a);else if(a.screen===SCREEN["home-connected"]&&sel===1)show(a,SCREEN["remapper-options"]);else if(sel===(a.screen===SCREEN["home-connected"]?2:1)){a.page=0;show(a,SCREEN["saved-devices"])}else show(a,SCREEN["learn-the-keys"])}break;case SCREEN["pair-new"]:case SCREEN["retry-pair-new"]:if(c===CONTROL.b){searchCancel(a);home(a)}else if(c===CONTROL.a&&a.screen===SCREEN["retry-pair-new"])pair(a);break;case SCREEN["remapper-options"]:if(c===CONTROL.left)home(a);else if(c===CONTROL.press)profilePage(a,a.selection);break;case SCREEN["passthrough-active"]:case SCREEN["passthrough-not-active"]:case SCREEN["standard-active"]:case SCREEN["standard-not-active"]:case SCREEN["escape-active"]:case SCREEN["escape-not-active"]:if(c===CONTROL.b)show(a,SCREEN["remapper-options"]);else if(c===CONTROL.left&&a.screen===SCREEN["escape-active"])home(a);else if(c===CONTROL.a&&[SCREEN["passthrough-not-active"],SCREEN["standard-not-active"],SCREEN["escape-not-active"]].includes(a.screen)){const p=a.screen===SCREEN["passthrough-not-active"]?PROFILE.PASSTHROUGH:a.screen===SCREEN["standard-not-active"]?PROFILE.STANDARD:PROFILE.ESCAPE,i=a.live?registryFind(a,a.live.mouse):-1;if(i>=0)a.registry[i].profile=p;profilePage(a,p)}break;case SCREEN["custom-edit"]:if(c===CONTROL.a){const i=a.live?registryFind(a,a.live.mouse):-1;if(i>=0)a.registry[i].profile=PROFILE.CUSTOM;a.custom=[...a.draft];a.customDirty=false;profilePage(a,PROFILE.CUSTOM)}else if(c===CONTROL.press){a.source=a.selection;show(a,SCREEN.left+a.source);a.selection=a.draft[a.source]}break;case SCREEN.left:case SCREEN.right:case SCREEN.middle:case SCREEN.forward:case SCREEN.backward:if(c===CONTROL.a){a.draft[a.source]=a.selection;a.customDirty=true;show(a,SCREEN["custom-edit"]);a.selection=a.source}break;case SCREEN["saved-devices"]:if(c===CONTROL.b)home(a);else if(a.registry.length&&(c===CONTROL.left||c===CONTROL.right))a.page=(a.page+a.registry.length+(c===CONTROL.left?-1:1))%a.registry.length;else if(c===CONTROL.press&&a.registry.length)show(a,SCREEN["remove-this"]);break;case SCREEN["remove-this"]:if(c===CONTROL.b)show(a,SCREEN["saved-devices"]);else if(c===CONTROL.a&&a.page<a.registry.length){const id=a.registry[a.page].id;if(a.live&&a.live.mouse===id)a.live=null;a.registry.splice(a.page,1);if(!a.registry.length)home(a);else{a.page%=a.registry.length;show(a,SCREEN["saved-devices"])}}}return true}
function tap(a,c){controlEvent(a,c,true);controlEvent(a,c,false)}function tick(a,d){a.now=(a.now+(d>>>0))>>>0;if(!searchExpired(a))return;const p=a.search.purpose;searchCancel(a);if(p===SEARCH.FIRST){if(!a.registry.length)searchStart(a,SEARCH.FIRST)}else if(p===SEARCH.SAVED){if(a.screen===SCREEN["home-searching"])show(a,SCREEN["home-retry"]);else if(a.screen===SCREEN["home-searching-help"])a.helpOwner=SCREEN["home-retry"]}else if(p===SEARCH.NEW){if(a.screen===SCREEN["pair-new"])show(a,SCREEN["retry-pair-new"]);else if(a.screen===SCREEN["help-pair-new"])a.helpOwner=SCREEN["retry-pair-new"]}}
function connect(a,id,name){id=Number(id);if(!Number.isInteger(id)||id<=0||!String(name||"").trim())return{ok:false,error:"invalid-mouse"};const idx=registryFind(a,id),saved=idx>=0,eligible=a.search.purpose!==SEARCH.NONE&&(a.search.purpose===SEARCH.SAVED?saved:!saved)&&!searchExpired(a);if(!eligible)return{ok:false,error:"mouse-not-eligible-for-current-search"};if(!saved&&a.registry.length>=SAVED_CAPACITY)return{ok:false,error:"saved-device-capacity"};const first=a.registry.length===0;if(!saved)a.registry.push({id,name:String(name).slice(0,NAME_CAPACITY-1),profile:PROFILE.PASSTHROUGH,bonded:true});a.nextSession=(a.nextSession+1)>>>0;if(!a.nextSession)a.nextSession=1;a.live={mouse:id,generation:a.nextSession};searchCancel(a);if(isHelp(a.screen)){if(isHome(a.helpOwner)||[SCREEN["pair-new"],SCREEN["retry-pair-new"]].includes(a.helpOwner))a.helpOwner=first?SCREEN["first-mouse-connected"]:SCREEN["home-connected"]}else if(first||isHome(a.screen)||[SCREEN["pair-new"],SCREEN["retry-pair-new"]].includes(a.screen))show(a,first?SCREEN["first-mouse-connected"]:SCREEN["home-connected"]);return{ok:true}}
function disconnect(a){if(!a.live)return false;a.live=null;if(isHome(a.screen))home(a);else if(a.screen===SCREEN["help-home-connected"])a.helpOwner=SCREEN["home-searching"];return true}
function view(a){let i=a.live?registryFind(a,a.live.mouse):-1;if(a.screen===SCREEN["saved-devices"]||a.screen===SCREEN["remove-this"])i=a.page<a.registry.length?a.page:-1;const m=i>=0?a.registry[i]:null;return{screen:a.screen,selection:a.selection,pressed:a.pressed,page:a.page,count:a.registry.length,draft:[...a.draft],name:m?m.name:"",profile:m?m.profile:PROFILE.PASSTHROUGH,connected:!!(m&&a.live&&a.live.mouse===m.id),customApplied:liveProfile(a)===PROFILE.CUSTOM&&!a.customDirty}}
function emptyFrame(){return{cells:Array.from({length:9},()=>Array.from({length:21},()=>({character:" ",tone:TONE.TITLE}))),hint:9,didactic:false}}function frameText(f,r,c,text,tone){if(r>=9)return;for(const ch of String(text)){if(c>=21)break;f.cells[r][c++]={character:ch,tone}}}function rowTone(f,r,t){for(let c=0;c<21;c++)f.cells[r][c].tone=t}function span(f,r,c,n){for(let i=0;i<n&&c+i<21;i++)f.cells[r][c+i].tone=TONE.WHITE}function replace(f,r,text,tone){for(let c=0;c<21;c++)f.cells[r][c]={character:" ",tone};frameText(f,r,0,text,tone)}function isDown(v,c){return!!(v.pressed&(1<<c))}
function project(v){const f=emptyFrame();f.didactic=isDidactic(v.screen);const id=screenId(v.screen),rows=screenRows(v.screen),help=id.includes("help");if(help)f.hint=8;if(!f.didactic&&!help)for(let r=1;r<9;r++)if(rows[r].startsWith("KEY ")||rows[r].startsWith("JOY ")||rows[r].startsWith("ANY KEY")){f.hint=r;break}for(let r=0;r<9;r++){const tone=r===0?TONE.TITLE:(f.didactic||r>=f.hint||rows[r][0]===" ")?TONE.ACTION:TONE.BODY;replace(f,r,rows[r],tone)}if(f.didactic){let r=v.screen===SCREEN["searching-first"]?3:1;if(isDown(v,CONTROL.up))span(f,r,7,6);if(isDown(v,CONTROL.left)){span(f,r+1,2,3);span(f,r+2,2,4)}if(isDown(v,CONTROL.press)){span(f,r+1,9,3);span(f,r+2,8,5)}if(isDown(v,CONTROL.right)){span(f,r+1,16,3);span(f,r+2,15,5)}if(isDown(v,CONTROL.down))span(f,r+3,6,8);if(v.screen===SCREEN["searching-first"]){if(isDown(v,CONTROL.a))span(f,7,1,5);if(isDown(v,CONTROL.x))span(f,7,15,5);if(isDown(v,CONTROL.b))span(f,8,1,5);if(isDown(v,CONTROL.y))span(f,8,15,5)}else{if(isDown(v,CONTROL.a))span(f,5,15,5);if(isDown(v,CONTROL.b)){span(f,6,15,5);span(f,6,0,11)}if(isDown(v,CONTROL.x)){span(f,7,15,5);span(f,7,1,10)}if(isDown(v,CONTROL.y))span(f,8,2,18)}return f}const name=displayName(v.name),p=v.profile<=PROFILE.CUSTOM?v.profile:PROFILE.PASSTHROUGH;let selected=-1;if(v.screen===SCREEN["home-connected"]){replace(f,0,homeTitle(v.name),TONE.TITLE);replace(f,2,p===PROFILE.PASSTHROUGH?" NO REMAP PASSTHROUGH":` REMAPPED TO ${PROFILE_NAMES[p]}`,TONE.ACTION);selected=1+v.selection}else if(v.screen===SCREEN["home-searching"]||v.screen===SCREEN["home-retry"])selected=1+v.selection;else if(v.screen===SCREEN["remapper-options"]){rowTone(f,1+p,TONE.CYAN);selected=1+v.selection}else if(v.screen===SCREEN["custom-edit"]){for(let i=0;i<5;i++)replace(f,1+i,` ${SOURCE_NAMES[i]} IS ${TARGET_NAMES[v.draft[i]<6?v.draft[i]:0]}`,v.customApplied?TONE.CYAN:TONE.ACTION);selected=1+v.selection}else if(v.screen>=SCREEN.left&&v.screen<=SCREEN.backward){const source=v.screen-SCREEN.left;rowTone(f,1+v.draft[source],TONE.CYAN);selected=1+v.selection}else if(v.screen===SCREEN["saved-devices"]){replace(f,0,`${v.count?v.page+1:0} OF ${v.count}`,TONE.TITLE);replace(f,1,name,v.connected?TONE.CYAN:TONE.BODY);replace(f,2,v.connected?"STATUS: CONNECTED":"STATUS: DISCONNECTED",TONE.BODY);replace(f,3,`PROFILE: ${PROFILE_NAMES[p]}`,TONE.BODY);selected=4}else if(v.screen===SCREEN["remove-this"])replace(f,1,name,TONE.BODY);else if([SCREEN["passthrough-active"],SCREEN["standard-active"],SCREEN["escape-active"]].includes(v.screen))for(let r=1;r<f.hint;r++)rowTone(f,r,TONE.CYAN);if(selected>=0&&selected<9)rowTone(f,selected,TONE.WHITE);for(let r=f.hint;r<9;r++)for(let c=0;c<9;c++)if(isDown(v,c)){let match=rows[r].includes(TOKEN_NAMES[c]);if((c===CONTROL.up||c===CONTROL.down)&&rows[r].includes("UP / DOWN"))match=true;if((c===CONTROL.left||c===CONTROL.right)&&rows[r].includes("RIGHT\\LEFT"))match=true;if(rows[r].includes("ANY KEY"))match=true;if(match)rowTone(f,r,TONE.WHITE)}return f}
function textY(f,row){if(row===0)return 8;if(f.didactic)return 39+(row-1)*25;if(row>=f.hint)return 214-(8-row)*26;return 39+(row-1)*26}function hintBoundary(f){return f.didactic?0:f.hint<9?textY(f,f.hint)-11:240}
function glyphRow(ch,row){if(row>=7)return 0;if(ch>="A"&&ch<="Z")return ALPHA[ch.charCodeAt(0)-65][row];if(ch>="0"&&ch<="9")return DIGIT[ch.charCodeAt(0)-48][row];if(ch==="-")return row===3?31:0;if(ch===":")return row===2||row===5?4:0;if(ch===".")return row===6?4:0;if(ch==="=")return row===2||row===4?31:0;if(ch==="/")return row<=4?1<<(4-row):0;if(ch==="\\")return row<=4?1<<row:0;if(ch===">")return[16,8,4,2,4,8,16][row];if(ch==="<")return[1,2,4,8,4,2,1][row];if(ch==="?")return[14,17,1,2,4,0,4][row];if(ch==="!")return row<5||row===6?4:0;if(ch===",")return row===5?4:row===6?8:0;if(ch==="(")return row===0||row===6?2:row===1||row===5?4:8;if(ch===")")return row===0||row===6?8:row===1||row===5?4:2;return 0}
function render565(f){const out=new Uint16Array(WIDTH*HEIGHT),boundary=hintBoundary(f);for(let y=0;y<HEIGHT;y++)out.fill(y<boundary?RGB565.BLACK:RGB565.DARK_MAGENTA,y*WIDTH,(y+1)*WIDTH);for(let r=0;r<9;r++)for(let c=0;c<21;c++){const cell=f.cells[r][c],x=7+c*11,y=textY(f,r),color=RGB565.TONES[cell.tone]||RGB565.LIGHT_GRAY;for(let py=0;py<14&&y+py<HEIGHT;py++){const bits=glyphRow(cell.character,Math.floor(py/2));for(let px=0;px<10&&x+px<WIDTH;px++)if(bits&(1<<(4-Math.floor(px/2))))out[(y+py)*WIDTH+x+px]=color}}return out}
function rgb565ToRgb(p){return[Math.floor(((p>>11)&31)*255/31),Math.floor(((p>>5)&63)*255/63),Math.floor((p&31)*255/31)]}function applyGain(v,g){return Math.min(255,Math.floor((v*g+50)/100))}function toRgba(pixels,gain,locked){const effective=locked?0:Math.max(0,Math.min(1000,Math.round(gain))),out=new Uint8ClampedArray(pixels.length*4);for(let i=0;i<pixels.length;i++){const rgb=rgb565ToRgb(pixels[i]),j=i*4;out[j]=applyGain(rgb[0],effective);out[j+1]=applyGain(rgb[1],effective);out[j+2]=applyGain(rgb[2],effective);out[j+3]=255}return out}
function stateSummary(a){const v=view(a);return{screen:screenId(a.screen),locked:a.locked,search:["NONE","FIRST","SAVED","NEW"][a.search.purpose],saved:a.registry.length,connected:!!a.live,selection:a.selection,page:a.page+1,mouse:v.name||"-",profile:PROFILE_NAMES[liveProfile(a)],now:a.now}}
const api={WIDTH,HEIGHT,CONTROL,PROFILE,TARGET,SEARCH,TONE,SCREEN,SCREEN_IDS,SCREEN_TEMPLATES,RGB565,createApp,createPersistent,snapshot,restore,home,pair,controlEvent,tap,tick,connect,disconnect,view,project,render565,toRgba,displayName,homeTitle,screenId,findScreen,stateSummary,liveProfile,applyGain};
if(typeof module!=="undefined"&&module.exports)module.exports=api;global.MBRWebCore=api})(typeof globalThis!=="undefined"?globalThis:this);
